folio-org/mod-licenses

- scripts/run_self_reg.sh
- service/.editorconfig
Ow, the last edit coincidentally took my .editorconfig with it during pushing. Would like to have one there anyway..
> Edit scripts

- README.md
- scripts/license_properties.jq
- scripts/load_single_license.sh
- service/grails-app/conf/application-vagrant-db.yml
> Documentation updates for https://issues.folio.org/browse/MODKBEKBJ-152

- README.md
See [FOLIO-1021](https://issues.folio.org/browse/FOLIO-1021)
> FOLIO-1021 Use range for copyright years

- scripts/load_single_license.sh
- service/grails-app/conf/application.yml
Dates still weren't working properly so I copied `mod-agreements` and changed:
- `yyyy-mm-dd` ➡️ `yyyy-MM-dd`
Tested and it looks like it does the trick.
> Fixed date format for ERM-1 and ERM-11

- service/grails-app/controllers/org/olf/licenses/OrgController.groovy
- service/grails-app/domain/org/olf/general/Org.groovy
- service/grails-app/domain/org/olf/licenses/License.groovy
- service/grails-app/domain/org/olf/licenses/LicenseOrg.groovy
- service/grails-app/services/org/olf/DependentModuleProxyService.groovy
- service/src/main/groovy/org/olf/general/annotations/OkapiDistributedDomain.groovy
- service/src/main/okapi/ModuleDescriptor-template.json
Bringing over the Organizations data model from mod-agreements. Much of the imported code will be removed later in ERM-26.
ERM-7 > ERM-25
> Bring over the Organizations data model from mod-agreements

- service/grails-app/domain/org/olf/licenses/LicenseOrg.groovy
Bring the role values inline with what's requested in [ERM-36](https://issues.folio.org/browse/ERM-36)
> ERM-36 LicenseOrg: Set correct role defaults

- scripts/license_properties.jq
- scripts/okapi-login
- scripts/register_and_enable.sh
- service/grails-app/domain/org/olf/general/DocumentAttachment.groovy
- service/grails-app/domain/org/olf/licenses/License.groovy
- service/grails-app/migrations/docs.groovy
- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/views/documentAttachment/_documentAttachment.gson
- service/grails-app/views/license/_license.gson
- service/grails-app/views/refdataValue/_refdataValue.gson
…ed test case to license_properties.jq, updated template gson files to improve rendering of some embedded types
> Work to support [ERM-37] adding document domain classes.

- service/grails-app/controllers/org/olf/licenses/InternalContactController.groovy
- service/grails-app/controllers/org/olf/licenses/UrlMappings.groovy
- service/grails-app/domain/org/olf/licenses/InternalContact.groovy
- service/grails-app/domain/org/olf/licenses/License.groovy
- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/migrations/update-mod-license-1-5-0.groovy
- service/grails-app/views/internalContact/_internalContact.gson
- service/grails-app/views/license/_license.gson
This PR had changes for adding internal contracts to licenses
> Add contracts

- service/build.gradle
This should complete [ERM-213]
> Just increment the module versions.

- service/build.gradle
- service/grails-app/conf/application.yml
- service/grails-app/domain/org/olf/licenses/InternalContact.groovy
- service/grails-app/domain/org/olf/licenses/License.groovy
- service/grails-app/domain/org/olf/licenses/LicenseAmendment.groovy
- service/grails-app/domain/org/olf/licenses/LicenseLink.groovy
- service/grails-app/domain/org/olf/licenses/LicenseOrg.groovy
- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/migrations/update-mod-license-1-7.groovy
- service/grails-app/views/error.gson
- service/grails-app/views/license/_license.gson
- service/grails-app/views/licenseAmendment/_licenseAmendment.gson
- service/grails-app/views/licenseCore/_licenseCore.gson
- service/src/integration-test/groovy/com/k_int/okapi/testing/HttpSpec.groovy
- service/src/integration-test/groovy/com/k_int/okapi/testing/OKAPISpec.groovy
- service/src/integration-test/groovy/org/olf/licenses/LicenseAmendmentSpec.groovy
- service/src/integration-test/groovy/org/olf/licenses/LicenseLifecycleSpec.groovy
- service/src/main/groovy/org/olf/licenses/LicenseCore.groovy
Amendments work complete with test cases.
> Feature/erm 82/amendments model

- service/grails-app/controllers/org/olf/licenses/CustomPropertDefinitionController.groovy
> Sort by label instead of name

- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/migrations/update-mod-license-2-2.groovy
- Migration file added
- Migration written
> ERM-783: Changed column type of custom properties description to 'text'

- Jenkinsfile
Add Jenkins Stage KubeDeploy within pipline.
> FOLIO-2546: Add Jenkins Stage KubeDeploy within pipline.

- service/build.gradle
- service/grails-app/i18n/messages.properties
> fix: Update TK and tidy messages.

- service/src/main/okapi/ModuleDescriptor-template.json
Quite possible fix for ERM-1079 too
> ERM-972: Missing permission definition

- service/src/main/okapi/ModuleDescriptor-template.json
> Remove duplicate licenses.licenseLinks.collection.get

- service/build.gradle
> update protocols for maven repos

- service/grails-app/domain/org/olf/licenses/License.groovy
- service/grails-app/domain/org/olf/licenses/LicenseOrg.groovy
- service/grails-app/domain/org/olf/licenses/LicenseOrgRole.groovy
- service/grails-app/i18n/messages.properties
- service/grails-app/migrations/update-mod-license-2-3.groovy
- service/grails-app/views/licenseOrg/_licenseOrg.gson
- service/grails-app/views/licenseOrgRole/_licenseOrgRole.gson
* add LicenseOrgRole doamin class, change License and LicenseOrg, refs ERM-1541, ERM-1543
* add view for licenseOrgRole, change licenseOrg view, add migration, refs ERM-1541
> ERM-1541 Support for multiple roles per organisation in Licenses

- service/grails-app/services/org/olf/licenses/LicenseHousekeepingService.groovy
added organizations cleanup method to housekeeping service
> ERM-1775: Regularly remove organizations that do not have any links to Licenses 

- service/src/main/groovy/org/olf/licenses/LicenseCore.groovy
Removed beforeInsert work, logic instead moved to client on frontend to better reflect model on backend
ERM-1849
> fix: ERM-1849

- NEWS.md
- service/gradle.properties
Changelog update and removed SNAPSHOT from version number
> Release v4.0.0

- NEWS.md
- service/gradle.properties
Bumped version and new section in changelog
> chore: post-release chore

- .github/CODEOWNERS
- README.md
- service/build.gradle
- service/grails-app/conf/application.yml
- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/migrations/update-mod-license-4-1.groovy
- service/grails-app/services/org/olf/licenses/LicenseHousekeepingService.groovy
upgrade web toolkit and add migrations.
> ERM-1943 Feature s3 storage 

- NEWS.md
- service/gradle.properties
Removed SNAPSHOT from version number, updated changelog
ERM-2009
> chore: Release 4.1.0

- NEWS.md
- service/gradle.properties
Bumped version to 4.2.0-SNAPSHOT on master, added changelog section
ERM-2009
> chore: VersionBump

- service/grails-app/controllers/org/olf/licenses/CustomPropertDefinitionController.groovy
- service/grails-app/controllers/org/olf/licenses/UrlMappings.groovy
- service/src/main/okapi/ModuleDescriptor-template.json
Added contexts endpoint to fetch list of Term contexts from licenses
ERM-2043
> feat: Contexts endpoint

- service/build.gradle
- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/migrations/update-mod-license-4-2.groovy
Bumped dep on web toolkit to get access to new custprop features: "retired" and LocalDate type properties
refs ERM-778, ERM-2044, ERM-2017
> feat: Web-Toolkit

- service/build.gradle
Added immutability to the "value" sets of Multi-Valued CustProps, which enables deletion
ERM-2218
> feat: MultiValued Custom Properties

- NEWS.md
- service/gradle.properties
Removed SNAPSHOT from version number and updated changelog section
ERM-2021
> chore: Release 4.2.0

- scripts/okapi-login
- scripts/register_and_enable_rancher.sh
- scripts/run_rancher_desktop.sh
- scripts/secure_enable.sh
- scripts/secure_register.sh
Adds scripts to enable running against a rancher desktop (KInt tooling only at the moment)
> chore: Added script files etc to run with rancher-desktop

- service/grails-app/conf/application-rancher-desktop-db.yml
Added yml file to allow running of module through grails run-app command in rancher desktop
> feat: Added yml file

- NEWS.md
- service/gradle.properties
Added NEWS.md details and removed SNAPSHOT from version #
ERM-2493
> chore: Release 4.3.0

- NEWS.md
- service/gradle.properties
Added NEWS.md section and bumped version -> 4.4.0
ERM-2493
> chore: post release

- NEWS.md
- service/grails-app/domain/org/olf/licenses/InternalContact.groovy
* remove defaults in InternalContact class
* update NEWS.md
> ERM-2885 Reduce number of internal contact role defaults in Licenses

- service/build.gradle
- service/grails-app/migrations/initial-customisations.groovy
Bumped versions of WTK and grails-okapi, added liquibase build.gradle handling
> chore: Fixes

- service/grails-app/views/licenseAmendment/_licenseAmendment.gson
* include owner in licenseAmendment view
> ERM-2993 Add amendments search in licenses app

- NEWS.md
- service/build.gradle
* update web-toolkit to version 8.1.0
* edit NEWS.md
> ERM-2966 Error when match and filter contain the same path root

- NEWS.md
- service/gradle.properties
Added details to NEWS.md and removed SNAPSHOT from version #
ERM-2651
> chore: Release 5.0.0

- service/build.gradle
build: Update version of 'com.github.everit-org.json-schema:org.everit.json.schema' (#251)
Updated version of 'com.github.everit-org.json-schema:org.everit.json.schema' to 1.14.3 to avoid DoS and OOM issue
refs ERM-3112, ERM-3117
> Release 5.0.2

- service/grails-app/migrations/module-tenant-changelog.groovy
- service/grails-app/migrations/update-mod-license-5-1.groovy
Added GIN indexes to all relevant database columns used within search
Added indexes for foreign keys
> ERM 3073: Identify and implement indexes

- service/grails-app/migrations/initial-customisations.groovy
- service/grails-app/migrations/update-mod-license-5-1.groovy
https://issues.folio.org/browse/ERM-3072
The extension is required for the gin index added in PR #253.
> ERM-3073: Create btree_gin extension for gin indexes

- service/build.gradle
build: Dependency upgrades
Bumped dependencies for security reasons
ERM-3175
> ERM-3175: Review outdated/vulnerable dependencies in mod-licenses

- NEWS.md
> docs: Include patch release notes on master branch

- service/grails-app/controllers/org/olf/licenses/export/ExportController.groovy
- manually bind json data to exportObj
> ERM-3208: Export license creates empty file

- NEWS.md
- service/gradle.properties
- service/grails-app/controllers/org/olf/licenses/export/ExportController.groovy
Updated NEWS.md and bumped gradle app version to 6.0.2
refs ERM-3213
> Release 6.0.2

- NEWS.md
- service/gradle.properties
- service/src/main/okapi/ModuleDescriptor-template.json
Added NEWS.md section and bumped version -> 6.0.3
- ERM-3290 Fix permission on /licenses/licenses/{id}/linkedAgreements
- ERM-3285 Fix permission on /licenses/files/{id}/raw in mod-licenses
ERM-3286
> Release 6.0.3

- NEWS.md
Added NEWS.md section from 6.0.3 release
> chore: Post release 6.0.3

- NEWS.md
- service/gradle.properties
- service/src/main/okapi/ModuleDescriptor-template.json
Added NEWS section and bumped version to 6.1.1
ERM-3439
> chore: Release 6.1.1

- NEWS.md
Added NEWS section reflected in release 6.1.1
> chore: Post-release 6.1.1

- NEWS.md
- service/build.gradle
- service/gradle.properties
Added NEWS section and bumped version to 6.1.2
ERM-3457
> Release 6.1.2

- NEWS.md
Added NEWS section reflected in release 6.1.2
> chore: Post-release 6.1.2

- NEWS.md
- service/build.gradle
- service/gradle.properties
Bumped version to 6.0.5, added NEWS.md section
ERM-3460
> Release 6.0.5

- NEWS.md
- service/build.gradle
- service/gradle.properties
PR for mod-licenses release 5.0.4
ERM-3459
> Release 5.0.4

- NEWS.md
> docs: Added env variable changes to release notes

- NEWS.md
- service/gradle.properties
Added NEWS.md section, bumped appVersion -> 6.3.0-SNAPSHOT, bumped okapiInterfaceVersion -> 6.3
> chore: Post release 6.2.0

- NEWS.md
Added NEWS.md section reflected in 6.2.1 release
> chore: Post release 6.2.1

- service/grails-app/conf/application.yml
- service/grails-app/services/org/olf/licenses/LicenseHousekeepingService.groovy
* add empty string fallback to application.yml
> ERM-3658 S3 secret key in Agreements and licenses app settings is pre-populated incorrectly

- service/build.gradle
Bumped undertow version to 2.2.37
ERM-3685
> ERM-3685: Upgrade undertow from 2.2.28.Final to 2.2.37.Final fixing vulns

- NEWS.md
Added NEWS.md section to reflect changes made in 6.2.2
> docs: Post release 6.2.2
