README.md
scripts/create_test_data.sh
scripts/license_properties.json
scripts/run_external_reg.sh
service/grails-app/conf/application.yml
service/grails-app/domain/org/olf/licenses/License.groovy
service/grails-app/migrations/create-mod-license.groovy
service/src/main/okapi/DeploymentDescriptor-template.json

Update the deployment descriptor to use port 8081
Update the run_external_reg.sh script to use --server.port=8081
Add parent property to license to model the scenario where a consortial member copies a consortial license and signs their copy - mostly as a test case for ui-plugin-find-license

This PR changes the default port to 8081, and adds parentLicense property

---

README.md
service/grails-app/controllers/org/olf/licenses/LicenseLinkController.groovy
service/grails-app/controllers/org/olf/licenses/UrlMappings.groovy
service/grails-app/views/license/_license.gson

Change to address the large cardinality of license links.

Change license resource so links are not included by default, provide licenseLinks endpoint instead.

---

service/grails-app/views/license/_license.gson
service/grails-app/views/licenseOrg/_licenseOrg.gson

- Expand `License`'s `orgs` array field
- Expand `LicenseOrg` the same way `SubscriptionAgreementOrg` is in mod-agreements.

ERM-7 LicenseOrg: Expand necessary fields

---

README.md
service/src/main/okapi/ModuleDescriptor-template.json

Added `licenses.agreements.linkedLicenses.get` to the `licenses.licenses.view` perm set. I'm not completely sure we want this, but it looks like what's needed to get the `/licenses/licenses/{id}/linkedAgreements` endpoint working for diku_admin.

Tweak linkedAgreements perms

---

service/grails-app/domain/org/olf/licenses/License.groovy
service/grails-app/migrations/update-mod-license-2-1.groovy

`localReference` field is to be used to hold LAS:eR reference data, so that we can eventually get away from relying on the naming conventions of the license. The same field name is used in agreements, and Pkg has a `reference` field we use.

PR to add localReference field to licenses

---

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_licenses_simple_search_widget.json

Removes isSet and isNotSet comporators from openEnded filter as they are not effective when endDateSemantics doesn't exist

ERM-1729: Update widget definition to remove non-required comparators

---

Jenkinsfile

These CI facilities replace the deprecated ones. See:
https://dev.folio.org/guides/api-lint/
https://dev.folio.org/guides/api-doc/

FOLIO-2898 FOLIO-2893 FOLIO-2917 Use new CI facilities api-doc and api-lint and api-schema-lint

---

scripts/upsert-licenses-refdata

The entries are taken from a JSON file passed as parameter to this script.
Intended usage: Deploy translated labels and additional entries commonly
used in a library union like GBV.
It uses desc and value for matching because id is different for each tenant.

ERM-1975: Script to insert and update /licenses/refdata entries

---

service/src/main/okapi/tenant/sample_data/widgetDefinitions/erm_licenses_simple_search_widget_1.1.json

Removed "!=" option for ogranizations array due to how that works for arrays in web-toolkit
ERM-2037

fix: Removed isNot

---

Jenkinsfile

Add new [api-lint](https://dev.folio.org/guides/api-lint/) arg for warnings. False by default.
And re-enable doApiLint.

FOLIO-3382 Add new api-lint warnings arg

---

service/grails-app/services/org/olf/licenses/export/ExportService.groovy

Terms exported as csv now result in a single column with `;` separated values.
ERM-2226

fix: Export MultiValued Terms

---

README.md

docs: ERM-2921 README addition
Added some module installation notes to mod-licenses README, specifying to use `loadReference=true`
ERM-2921

ERM-2921: File Storage option missing in License application

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
.gitignore
Jenkinsfile
README.md
ramls/licenses.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 ERM-2927 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

.gitignore
service/build.gradle

build: spring-webmvc
Directly implemented dep on spring-webmvc 5.3.28 to avoid possible security vulnerability
refs ERM-2940

ERM-2940: spring-webmvc 5.3.25 security bypass vulnerability

---

NEWS.md
service/gradle.properties
service/grails-app/conf/application-dc.yml

build: Poppy: grails 5.3.6 fixing databinding DoS (https://github.com/advisories/GHSA-3pjv-r7w4-2cf5)
Fixed grails version pulling in databinding library with security issue. Included application-dc profile yaml
ERM-3138

Release 5.0.3

---

service/src/main/okapi/ModuleDescriptor-template.json

- Remove the licenses.files.view subpermission from licenses.files.item.download perm in mod-licenses module descriptor

ERM-3285: Fix permission on /licenses/files/{id}/raw in mod-licenses

---

service/src/main/okapi/ModuleDescriptor-template.json

Removed licenses.agreements.linkedLicenses.get permission

ERM-3290: Fix permission on /licenses/licenses/{id}/linkedAgreements

---

service/src/main/okapi/ModuleDescriptor-template.json

build: Add optional okapi dependencies to ModuleDescriptor
ERM-3420

ERM-3420: Missing interface dependencies in module descriptor in mod-licenses

---

service/build.gradle

build: Add minio dependency in mod-licenses
mod-licenses was missing minio dependencies (These are reflecting mod-agreements versions and backports may need other versions--to check)
ERM-3458

ERM-3458: Add minio dependency in mod-licenses

---

service/build.gradle

feat: S3 Environment variable
Now available via WTK 10.1.0 -- the ability to set a GLOBAL_S3_SECRET_KEY which acts as a _fallback_ for all tenants if the pre-existing AppSetting is not set.
refs ERM-3470

ERM-3470: S3 environment variable settings

---

Jenkinsfile
service/grails-app/services/org/olf/licenses/LicenseHousekeepingService.groovy

build: Remove string fallbacks for S3 env variable
S3 environment variable should be `null` when it has not been configured.
refs ERM-3470

ERM-3470: fix -- remove S3 environment variable string fallback

---

service/build.gradle

Bumped dependencies for minio, kafka-clients and jackson, fixing vulnerabilities
ERM-3688

ERM-3688: minio 8.5.17, kafka-clients 3.7.2, jackson 2.18.3 fixing vulns
